spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/habr
    username: postgres
    password: Sq1357E
    driverClassName: org.postgresql.Driver